config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'home#top'

get 'home/about' => 'home#about', as:'about'

resources :books, only:[:create, :index, :show, :edit, :destroy, :update,]

resources :users, only:[:index, :show, :edit, :update,]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user

	validates :title,:body, presence: true

	validates :title,:body, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   validates :name, presence: true, length: {in: 2..20}

   validates :introduction, length: {maximum: 50}

   has_many :books, dependent: :destroy

   attachment :profile_image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :configure_permitted_parameters,if: :devise_controller?


def after_sign_out_path_for(resource)
    root_path
end

def after_sign_in_path_for(resource)
    user_path(current_user.id)
end


protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up,keys:[:email, :name])
  devise_parameter_sanitizer.permit(:sign_in,keys:[:name])


end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :authenticate_user!

before_action :set_book, only: [:update, :edit]


	def create
		@book = Book.new(book_params)
    	@book.user_id = current_user.id
		if @book.save
		   redirect_to book_path(@book.id), notice: "You have creatad book successfully."
		else
			@books = Book.all
			render :index
		end
	end

	def index
		@books = Book.all
		@book = Book.new
    end

	def show
		@book = Book.find(params[:id])
		@books =Book.new
		@user = User.find(@book.user_id)
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
		   redirect_to book_path(@book.id),notice: "You have updated book successfully."
		else
			render :edit 
	    end
	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to books_path
	end


   private
   def user_params
    params.require(:user).permit(:name, :profile_image, :introduction,)
    end

   def book_params
   	params.require(:book).permit(:title, :body,)
   end

   def set_book
   	     book = Book.find(params[:id])
   	  if book.user_id == current_user.id
      else
         redirect_to books_path
      end
   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate_user!

before_action :set_user, only: [:update, :edit]

	def index
		@book = Book.new
		@users = User.all
	end

	def show
		@book = Book.new
		@books= Book.where(user_id: params[:id])
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end


	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
		   redirect_to user_path(@user.id), notice: "You have updated user successfully."
		else
		   render :edit
		end
	end

	private


    def user_params
    params.require(:user).permit(:name, :profile_image, :introduction,)
    end

    def set_user
   	     user = User.find(params[:id])
   	  if user.id == current_user.id
      else
         redirect_to user_path(current_user)
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
<div class="row">
	<% if @book.errors.any? %>
    <p><%= @book.errors.count %>errors prohibited this book from being saved:</p>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
<% end %>
	<div class="col-md-offset-3 col-md-5">
<h1>Editing Book</h1>
<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title,class: "form-control" %>
    <h4>Opinion</h4>
    <%= f.text_area :body,class: "form-control" %><br>
    <%= f.submit 'Update Book',class: "btn btn-primary btn-block " %>
    <%= link_to "Show",book_path(@book.id) %>
    <%= link_to "Back",books_path %>
<% end %>
</div>
</div>
</div>

app/views/books/index.html.erb
<div class="container"> 
  <div class="row">
<% if @book.errors.any? %>
    <p><%= @book.errors.count %>errors prohibited this book from being saved:</p>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
<% end %>

<div class="col-xs-3">
<h2>User info</h2>
<%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
    <table class="table">
      <tbody>
        <tr>
          <td>name</td>
          <td><%= current_user.name %></td>
        </tr>
        <tr>
          <td>introduction</td>
          <td><%= current_user.introduction %></td>
        </tr>
      </tbody>
    </table>
<%= link_to "",edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>

<h2>New book</h2>
<div class="form-group">
<%= form_for(@book,url: '/books') do |f| %>
    <p>Title</p>
      <%= f.text_field :title,class: "form-control" %>
    <p>Opinion</p>
      <%= f.text_area :body,class: "form-control"%>
    <br>
      <%= f.submit 'Create Book',class: "btn btn-primary btn-block" %>
<% end %>
</div>
</div>

<div class="col-xs-9">
<h2>Books</h2>

  <table class="table table-hover table-inverse">
     <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
    </thead>
<% @books.each do |book| %>
    <tbody>
  	  <tr>
        <td><%= link_to user_path(book.user), target: "_blank" do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %>
        <% end %></td>
        <td><%= link_to "#{book.title}",book_path(book.id) %></td>
        <td><%= book.body %></td>
      </tr>
    </tbody>
   <% end %>
  </table>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container"> 
<div class="row">

<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<div class="col-xs-3">
  <h2>User info</h2>
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr>
            <td>name</td>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <td>introduction</td>
            <td><%= @user.introduction %></td>
          </tr>
        </tbody>
      </table>
    <%= link_to "",edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
<h2>New book</h2>
  <%= form_for(@books,url: '/books') do |f| %>
    <p>Title</p>
      <%= f.text_field :title,class: "form-control" %>
    <p>Opinion</p>
      <%= f.text_area :body,class: "form-control" %>
    <br>
      <%= f.submit 'Create Book',class: "btn btn-primary btn-block" %>
  <% end %>
</div>

<div class="col-xs-9">
  <h2>Book detail</h2>
    <table class="table table-hover table-inverse">
     <tbody>
    	<tr>
        <th><%= attachment_image_tag current_user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %><br>
          <%= link_to "#{@user.name}",user_path(@user.id) %></th>
        <th><%= link_to "#{@book.title}",book_path(@book.id) %></th>
        <th><%= @book.body %></th>
      <% if @user == current_user %>
        <th><%= link_to "Edit",edit_book_path(@book.id) %></th>
        <th><%= link_to "Destroy", book_path(@book.id), method: :delete, data: { confirm: '本当に消しますか？' }%></th>
      <% end %>
    </tbody>
    </table>
  </div>
 </div>
</div>
</div>

app/views/home/about.html.erb
<html>
<head>
</head>
<body>
<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers!</strong></span></h1>
</body>
</html>

app/views/home/top.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<div class="container"> 
	<div class="row">
		<div class=" col-md-offset-3 col-md-6">
			<div class="text-left">
<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers</strong></span> !!</h1>
  <p>In <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers,</strong></span></p>
  <p>you can share and exchange your opinions , inpressions , and emotions</p>
  <p>about various books!</p>
            </div>
        </div>
     </div>
<div class="row">
	<div class="col-md-offset-3 col-md-6">
		<div class="text-center">
  <%= link_to "Log in",new_user_session_path,class: "btn btn-primary btn-block" %>
        </div>
    </div>
</div>
<div class="row">
	<div class="col-md-offset-3 col-md-6">
		<div class="text-center">
  <%= link_to "Sign up",new_user_registration_path,class: "btn btn-success btn-block" %>
        </div>
    </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <title>Bookers2</title>
<div class="row">
<nav class="navbar navbar-inverse ">
<div class="col-xs-3">
<h2 class="title">Bookers</h2>
</div>
<div class="userif">
<div class="text-right">
<div class="col-xs-9">
  <% if user_signed_in? %>
  <button class="btn btn-link" type="button">
  <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
    <%= link_to "Home", user_path(current_user.id),class: "text-muted" %>
  </button>
  <button class="btn btn-link" type="button">
  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
    <%= link_to "Users", users_path,class: "text-muted" %>
  </button>
  <button class="btn btn-link" type="button">
  <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
    <%= link_to "Books", books_path,class: "text-muted" %>
  </button>
  <button class="btn btn-link" type="button">
  <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
    <%= link_to "logout", destroy_user_session_path, method: :delete,class: "text-muted" %>
  </button>
    <% else %>
  <button class="btn btn-link" type="button">
  <span class="glyphicon glyphicon-home" aria-hidden="true"> </span>
    <%= link_to "Home", root_path,class: "text-muted" %>
  </button>
  <button class="btn btn-link" type="button">
  <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
    <%= link_to "about",about_path,class: "text-muted" %>
  </button>
  <button class="btn btn-link" type="button">
  <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
    <%= link_to "sign up", new_user_registration_path,class: "text-muted" %>
  </button>
  <button class="btn btn-link" type="button">
  <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
    <%= link_to "login", new_user_session_path, notice: "Signed out successfully.",class: "text-muted" %>
  </button>
  <% end %>
</div>
</nav>

<div class="container"> 
  <body>
    <%= yield %>
  </body>
  <footer>
    <div class="text-right">
      <p>CopyRight Infratop.inc</p>
    </div>
  </footer>
  </div>
  </div>
</div>
</div>
</html>

app/views/users/edit.html.erb
<div class="container"> 
  <% if @user.errors.any? %>
    <p><%= @user.errors.count %>errors prohibited this book from being saved:</p>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
<% end %>

<h2>User info</h2>

<%= form_for(@user, url: user_path(@user.id), method: :patch) do |f| %>
<div class="row">
  <div class="col-xs-1">
    <p>Name</p>
  </div>
  <div class="col-xs-4">
    <%= f.text_field :name %>
  </div>
</div>
  <p>Image</p>
    <%= f.attachment_field :profile_image %>
      <br>
<div class="row">
  <div class="col-xs-1">
    <p>Intoroduction</p>
  </div>
  <div class="col-xs-3">
    <%= f.text_area :introduction %>
  </div>
      <br>
</div>
  <%= f.submit "Update User" %>
<% end %>
</div>

app/views/users/index.html.erb
<div class="container"> 
  <div class="row">

<div class="col-xs-3">
<h2>User info</h2>

<%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
    <table class="table">
      <tbody>
        <tr>
          <td>name</td>
          <td><%= current_user.name %></td>
        </tr>
        <tr>
          <td>introduction</td>
          <td><%= current_user.introduction %></td>
        </tr>
      </tbody>
    </table>
<%= link_to "",edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>


<h2>New book</h2>
<%= form_for(@book,url: '/books') do |f| %>
    <p>Title</p>
      <%= f.text_field :title,class: "form-control" %>
    <p>Opinion</p>
      <%= f.text_area :body,class: "form-control" %>
    <br>
      <%= f.submit 'Create Book',class: "btn btn-primary btn-block" %>
<% end %>
</div>
<div class="col-xs-9">
<h2>Users</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
      </tr>
    </thead>
<% @users.each do |user| %>
    <tbody>
  	  <tr>
        <th><%= attachment_image_tag current_user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %></th>
        <th><%= user.name %></th>
        <th><%= link_to "Show",user_path(user.id) %></th>
      </tr>
    </tbody>
<% end %>
  </table>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container"> 
<div class="row">

<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<div class="col-xs-3">
  <h2>User info</h2>
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr>
            <td>name</td>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <td>introduction</td>
            <td><%= @user.introduction %></td>
          </tr>
        </tbody>
      </table>
  <%= link_to "",edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
<h2>New book</h2>
  <%= form_for(@book,url: '/books') do |f| %>
    <p>Title</p>
      <%= f.text_field :title,class: "form-control" %>
    <p>Opinion</p>
      <%= f.text_area :body,class: "form-control" %>
    <br>
      <%= f.submit 'Create Book',class: "btn btn-primary btn-block" %>
  <% end %>
</div>

<div class="col-xs-9">
<h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
    </thead>
    <% @books.each do |book| %>
    <tbody>
      <tr>
        <th><%= attachment_image_tag current_user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %></th>
        <th><%= link_to "#{book.title}",book_path(book.id) %></th>
        <th><%= book.body %></th>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>
</div>
</div>